services:
#    galerie.example:
#        class: GalerieBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
parameters:
    images_directory: '%kernel.project_dir%/web/uploads/images'