<?php

namespace GalerieBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{

	public function getCommentaireGalerie($commentaire)
	{
		$qb = $this->createQueryBuilder('a');

		if($commentaire)
			$qb->where('a.commentaire = :id')->setParameter('id', $commentaire);


		return $query = $qb->getQuery()->getResult();
	}

}
