<?php
namespace GalerieBundle\Repository;
/**
 * GalerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalerieRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAllGalerieByCategorie($order,$categorie,$page,$recherche)
	{
		$qb = $this->createQueryBuilder('a');

		if($order)
			$qb->orderBy('a.categorie', $order);
		if($categorie)
			$qb->where('a.categorie = :cat')->setParameter('cat', "$categorie");
		if($recherche)
			$qb->where('a.title LIKE :recherche')->setParameter('recherche', "%$recherche%");

		if($page)
			$qb->setFirstResult(($page-1)*3)->setMaxResults(3);

		return $query = $qb->getQuery()->getResult();
	}

	public function getNbPageGalerie($categorie,$recherche)
	{
		$qb = $this->createQueryBuilder('a');
		$qb->select('COUNT(a)');

		if($categorie)
			$qb->where('a.categorie = :cat')->setParameter('cat', "$categorie");
		if($recherche)
			$qb->where('a.title LIKE :recherche')->setParameter('recherche', "%$recherche%");

		return $query = $qb->getQuery()->getResult();
	}
}