<?php
namespace GalerieBundle\Repository;
/**
 * GalerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalerieRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAllGalerieByCategorie($order,$categorie,$page)
	{
		$qb = $this->createQueryBuilder('a');

		if($order)
			$qb->orderBy('a.categorie', $order);
		if($categorie)
			$qb->where('a.categorie = :cat')->setParameter('cat', "$categorie");

		if($page)
			$qb->setFirstResult(($page-1)*20)->setMaxResults(20);

		return $query = $qb->getQuery()->getResult();
	}

	public function getNbPageGalerie($categorie)
	{
		$qb = $this->createQueryBuilder('a');
		$qb->select('COUNT(a)');

		if($categorie)
			$qb->where('a.categorie = :cat')->setParameter('cat', "$categorie");


		return $query = $qb->getQuery()->getResult();
	}
}