contact:
    resource: "@ContactBundle/Resources/config/routing.yml"
    prefix:   /

galerie:
    resource: "@GalerieBundle/Resources/config/routing.yml"
    prefix:   /

pagebasique:
    resource: "@PageBasiqueBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@PageBasiqueBundle/Controller/PageController.php"
    type:     annotation

logout:
    path: /logout